"""add is available to rooms

Revision ID: 41c86fa84673
Revises: 956611e0c38d
Create Date: 2025-06-22 18:01:46.269275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c86fa84673'
down_revision: Union[str, Sequence[str], None] = '956611e0c38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'rooms',
        sa.Column('is_available', sa.Boolean(), nullable=False, server_default=sa.true())
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_available')
    # ### end Alembic commands ###
